### ISSUE TITLE
What do you mean by type checking?

### ISSUE THREAD

**Issue by qrilka** [AndrewRademacher/game-of-life#4]
I your post you write

> ...overhead for calling that function. Type checking has to occur,...

What do you mean by type checking here? Haskell is statically typed and all type checks are done at compile time if you don't do it explicitly by using something like `Typeable`

**Comment by AndrewRademacher** [comment]
Type checking may be the wrong word here. It's not that a running Haskell program has to check for the correctness of a type when calling a function. It is that the program must, when calling a typeclass function, select which version of a function to dispatch on. Under the hood, a typeclass function looks up which implementation to use in a hash map at run time. The exception to this would be that if a function is inlined, the compiler will inline the specialized implementation directly with out any of the lookup code. 

If I'm recalling correctly what I was attempting to describe when I wrote the article, it should say something about the hash map lookup. Would that make more sense?

**Comment by qnikst** [comment]
No that wouldn't, if method can be specialized (it's big and there is no specialize, inline or INLINEABLE pragmas, or it's existential value) then a dictionary is passed to the function. but you should know that it's not a Python dictionary that is basically a hashmap, it's a C struct, so calling polymorphic value is just an indirect jump.

**Comment by qnikst** [comment]
You can read more on the topic for example in http://okmij.org/ftp/Computation/typeclass.html

**Comment by qrilka** [comment]
Could you explain where do you get that "hashmap lookup" from?
Maybe it stems from "dictionary passing" technique for type class implementation? 
I guess the word "dictionary" is a bit misleading in this case. But e.g. quoting http://okmij.org/ftp/Computation/typeclass.html :
> The type-class declaration Show a in Haskell translates to the data type declaration for the record 'a show, a dictionary. The name of a type class method becomes the label in the dictionary.
Thus "dictonary" in this case is something like a `vtable` in C++ - a table of function pointers. And so the overhead (if GHC fails to specialize type class call) is an extra jump.

**Comment by AndrewRademacher** [comment]
I'm going to take a look into the link that @qnikst provided this evening. Hopefully I can straighten out my own understanding of how typeclasses are implemented, then be able to fix the paragraph as a whole.

**Comment by AndrewRademacher** [comment]
@qrilka, I'm actually not sure where my mind came up with hashmap look up. I went back to my original materials, and even in the [video](https://www.youtube.com/watch?v=6COvD8oynmI&t=1239s) that I had initially watched about typeclasses shows it implemented as a dictionary plain as day. I'm just going to chalk it up to the fact that I wrote this article 4 years ago when I was still very new to Haskell.

@qnikst after reviewing both the SPJ video and the article that you sent me, I don't see any error in my understanding of typeclasses other than the confusion around hashmap lookup vs record/dictionary jump. Do you see anything else missing?

The original sentience is as follows.
```
Type checking has to occur, parameters have to be passed across CPU registers, a new variable scope has to be created, etc.
``` 

I intend to replace it with.
```
A new stack frame must be allocated, parameters must be passed across CPU registers, etc.
```

While passing a dictionary along with the parameters of the function call does have overhead. I would imagine a single or double pointer jump to be fairly trivial relative to the rest of the rigamarole that goes into a function call. Especially by the second time you call the function, assuming the pointer values were not flushed from cache.

**Comment by qnikst** [comment]
Looks good to me, if you want you may tell that functions may be specialized and then dictionary passing is removed, but that is a specific details about optimization.

**Comment by qrilka** [comment]
And with that I close the issue :)
